### PR TITLE
Adds support to install operator on CRC clusters with OLM integration

### PR DESCRIPTION
**Pull request by jvrahav**
This PR adds support for installing operator on openshift clusters.
This also brings in support to install operator on a CRC cluster using makefile commands

**What type of PR is this?**
kind enhancement

**What this PR does / why we need it**:
This adds files that are required to install operator in opernshift clusters through OLM. In addition this PR also adds makefile command to deploy the operator in a CRC cluster

**Test Report Added?**:
kind TESTED

**Test Report**:
Ran make deploy-crc command and verified that the operator was deployed in CRC successfully.

### CODE REVIEW

**Review by lgayatri — APPROVED** [review]
LGTM

**Review by aggarwalta — APPROVED** [review]
LGTM, thanks!

**Review by ridaz — APPROVED** [review]
LGTM, Thanks.

**Review by asifdxtreme — APPROVED** [review]
LGTM

**Pull request merged**
